animal(dog).
animal(cat).
animal(mouse).
animal(duck).
animal(eagle).
animal(cow).
animal(pig).
animal(horse).
animal(zebra).
animal(lion).   
animal(tiger).
animal(fox).
animal(wolf).
animal(bear).
animal(owl).
animal(raven).
animal(seagull).
animal(penguin).
animal(swan).
animal(duck).
animal(eagle).
animal(cow).
animal(pig).
animal(horse).
animal(zebra).
animal(lion).
animal(tiger).
animal(fox).
animal(wolf).
animal(bear).
animal(owl).
animal(raven).
animal(seagull).
animal(penguin).
animal(swan).
animal(duck).